version: "2"         # required to adjust maintainability checks
checks:
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 10
  method-count:
    enabled: false
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
